name: CI
on: [push]
jobs:
  test-typings-compile:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: npm install typescript
    - run: npm test

  test-usage-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: ./test-usage.sh
